[pytest]
python_files = *.test.py test_*.py
python_classes = Test*
python_functions = test_*
testpaths = app
norecursedirs = __pycache__
addopts = --ignore=app/main.test.py --ignore=app/main.integration.test.py --ignore=app/services/data_import.test.py
